spring.application.name=api-gateway
spring.data.mongodb.uri=mongodb://localhost:27017/api_gateway
spring.data.mongodb.database=api_gateway

server.port=8080
spring.cloud.gateway.server.webflux.routes[0].id=backend-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/api/(?<segment>.*), /${segment}
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=1
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.requestedTokens=1
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.key-resolver=#{@ipKeyResolver}
